syntax on
set background=dark

set expandtab
set tabstop=4

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'rust-lang/rust.vim'
Plugin 'cespare/vim-toml'
call vundle#end()
filetype plugin indent on
